### ISSUE TITLE
Getting Internal Server error while deployment of recording bot at command az aks create 

### ISSUE THREAD

**Issue by jinik21** [vasalis/TeamsRecordingBotAndAzureCongitiveServicesAtWork#111]
Getting Internal Server error while deployment of recording bot at command az aks create

**Comment by vasalis** [comment]
Hello @jinik21, could please elaborate a bit?
Did the previous steps work ok?
Some logs would be helpful...

**Comment by jinik21** [comment]
while running 3rd workflow : 02_Initial_Setup_All_Infra
in setup for aks cluster. the process give internal server error.
ref:
https://github.com/jinik21/TeamsRecordingBot/runs/6956686726?check_suite_focus=true

**Comment by jinik21** [comment]
> Hello @jinik21, could please elaborate a bit? Did the previous steps work ok? Some logs would be helpful...

yeah till aks create all steps worked fine and resources for middleware were also created.
The problem came with aks create and after that all other commands failed. though workflows for middleware and frontend passed.
