### ISSUE TITLE
Getting error while installing cert-manager

### ISSUE THREAD

**Issue by jinik21** [vasalis/TeamsRecordingBotAndAzureCongitiveServicesAtWork#112]
Unable to get through step setup all infra

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "certificaterequests.cert-manager.io" namespace: "" from "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "certificates.cert-manager.io" namespace: "" from "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

ensure CRDs are installed first, resource mapping not found for name: "cert-manager-controller-ingress-shim" namespace: "" from "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"

logs:
https://github.com/jinik21/TeamsRecordingBot/runs/6980721332?check_suite_focus=true

**Comment by vasalis** [comment]
have a look [here](https://github.com/kubeflow/manifests/issues/2028).
This is probably due to the version of k8s, so try adding the --kubernetes-version 1.20.x - this will define the k8s version.

**Comment by jinik21** [comment]
> --kubernetes-version 1.20.x

azure no longer supports this version of kubernetes

**Comment by jinik21** [comment]
Tried other way around changed cert-mananger version
ref:
https://github.com/jinik21/TeamsRecordingBot/blob/master/03_IaC/00_AzureCLI/02_AKS_iac.ps1

but still all the steps working fine but can't get kubectl get cert -n teams-recording-bot working. tls-ingress still not ready.
any help on that?
